version: "3.8"
services:
  document:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/app/src
      - ./nodemon.json:/usr/app/nodemon.json
    container_name: document-container
    expose:
      - "5000"
    ports:
      - "5000:5000"
    command: npm run dev
